### ISSUE TITLE
How do I get the full Path?

### ISSUE THREAD

**Issue by pedrotst** [ocaml/merlin#1147]
Consider the following example
```
module Foo = struct
  module Bar = struct
    type 'a x =
    | Nil
  end

  let myterm : int Bar.x = Bar.Nil
end
```

The type of `myterm` is a `Tconstr (Bar.x, ...)`
What's the easiest way to transform the Path `Bar.x` to `Foo.Bar.x`?

**Comment by pedrotst** [comment]
Should I assume there is no easy way to achieve this?

**Comment by trefis** [comment]
There is not indeed.
When you are inside of `Foo`, the name `Foo` doesn't exist.

**Comment by pedrotst** [comment]
Is there a documentation on how the scopes works anywhere?

**Comment by let-def** [comment]
I have seen the way ML environment works described as an "hyperstatic environment":
[tentative link to a relevant quote in google book](https://books.google.fr/books?id=81mFK8pqh5EC&pg=PA119&lpg=PA119&dq=lisp+in+small+pieces+hyperstatic&source=bl&ots=2LuXIK2c92&sig=ACfU3U3-jWC-7xGrAkqS88HFt_ogW2K7-Q&hl=fr&sa=X&ved=2ahUKEwilzOSOvb3qAhXqxoUKHdc7BeUQ6AEwAHoECAoQAQ#v=onepage&q&f=false).

Basically you cannot refer to a name before it is defined (as opposed to languages that have a separate notion of declaration and definition, with the caveat that you can refer to undefined names).
The only exception is the explicit `rec` keyword in front of recursive constructions which lifts the restriction for the group of objects being defined.

So that's how scoping works in ML. But it seems that you are also manipulating the internal representation of OCaml, we might help more if we know what your goal is.

**Comment by pedrotst** [comment]
Thank you @let-def for the interest and the details. This is a very interesting book overall, thanks for bringing it to my attention.

My goal is to implement a much simpler version of `Env` for [coq-of-ocaml](https://github.com/clarus/coq-of-ocaml). Currently we rely on `Env` for this, but every time we translate a `Types.tConstr (p, _)` we need to recompile the whole type definition pointed by `p` to fetch some compiled information.

My simple idea was to store a map of the translated type definitions by the "full path". But apparently I will need the a similar structure implemented by `Env`, i.e. an environment layered by modules.
