### ISSUE TITLE
3.4.0 vs `-error-style` flag

### ISSUE THREAD

**Issue by jberdine** [ocaml/merlin#1176]
Merlin 3.4.0 seems unhappy with `-error-style short` where 3.3.9 was ok. In cases where `dune` contains `(flags (... -error-style short)`, the emacs integration issues warnings about `-error-style` being an unknown flag.

I'm sorry but I don't have time to construct a small repro right now, I can try later if the root cause isn't clear.

**Comment by trefis** [comment]
Merlin does indeed complain about flags it doesn't know how to interpret, I though that was always the case but perhaps that's only true since we've move the loading of the configuration to an external process.

In any case, that flag is known to the compiler, so merlin should accept it (even if just to ignore it).
