### ISSUE TITLE
Type enclosing confuses module names and type constructors

### ISSUE THREAD

**Issue by voodoos** [ocaml/merlin#1226]
Given the program:

```ocaml
module Foo = struct
  let bar = 42
end

type t = Foo of int

let a = Foo 3
```

Asking the type for `Foo` in `Foo 3` merlin will answer `sig val bar : int end` instead of `t`.

**Comment by trefis** [comment]
We have some code in `Type_enclosing` to prevent producing a small enclosing when the cursor is on a constructor, but looking at the log for this example, it seems that the context we get is not precise enough:
```
# 0.01 context - inspect_context                                                                            
current node is: [[ expression; expression; value_binding; structure_item; structure ]]                     
# 0.01 context - inspect_context                                                                            
current enclosing node is: expression
```
I managed to reproduce on version 3.3.3, so it doesn't seem to be regression due to the changes to the context detection.

When I add some more logging to `context.ml` however, to see what the expression under the cursor is, I see this:
```
# 0.01 context - inspect_expression
expression (test.ml[5,59+12]..test.ml[5,59+13])
  Texp_constant Const_int 3
```
and indeed:
```
# 0.00 context - inspect_context
current node is: [[ expression (5:12 - 5:13); expression (5:8 - 5:13); value_binding (5:0 - 5:13);
                    structure_item (5:0 - 5:13); structure (1:0 - 5:13) ]]
```

There seem to be two issues here:
- the input of our context analysis functions seems incorrect (`Mtyper.node_at` is apparently at fault)
- we're failing to discard irrelevant (because not enclosing) AST chunks.

I'll have a look at all this.
