### ISSUE TITLE
document doesn't work reliably in source files

### ISSUE THREAD

**Issue by copy** [ocaml/merlin#1508]
For example, it doesn't work when the expression after a toplevel let is on its own line:

```
% cat test.ml 
let foo =
  ()
(** COMMENT *)

let () = foo
% cat test.ml | ocamlmerlin single document -position 5:11 
{"class":"return","value":"No documentation available","notifications":[],"timing":{"clock":1,"cpu":1,"query":0,"pp":0,"reader":0,"ppx":0,"typer":1,"error":0}}
```

While this works as expected:

```
% cat test.ml 
let foo = ()
(** COMMENT *)


let () = foo
% cat test.ml | ocamlmerlin single document -position 5:11 
{"class":"return","value":"COMMENT","notifications":[],"timing":{"clock":1,"cpu":1,"query":0,"pp":0,"reader":0,"ppx":0,"typer":1,"error":0}}
```

**Comment by voodoos** [comment]
In your examples the comment placement does not respect the ocamldoc specification: [in `ml` files](https://v2.ocaml.org/manual/ocamldoc.html#sss:ocamldoc-comments-ml) comments should always be placed before the element.

Comments can only appear after the element [in `mli` files](https://v2.ocaml.org/manual/ocamldoc.html#sss:ocamldoc-mli).

I guess the reason is that implementations can often be very long: it seems more useful to have the comment at the beginning.

Closing since it is not a Merlin issue.
