### ISSUE TITLE
Some executables should install to /usr/libexec and not /usr/bin

### ISSUE THREAD

**Issue by SnarkBoojum** [ocaml/merlin#1641]
Executables not meant for direct user usage but as helpers for other binaries should probably go to /usr/libexec and not /usr/bin.

**Comment by voodoos** [comment]
Not sure how you installed Merlin but if it was via `opam` which is the recommended setup then the binary should stays in your switch folder. For other installations we could consider it but given that `libexec` is, by design, not in the default `PATH` this could break editor plugins (and some of them are developed by external teams) so I don't see it happening soon.
