### ISSUE TITLE
emacs' merlin-mode highlighting of code w/ errors is just bad

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/merlin#1663]
Putting a lot of code in a bold pinkish font is just not helpful.
That makes the whole code completely unreadable.
I have to disable merlin-mode so that I can continue
working on the code in question...

https://discuss.ocaml.org/t/emacs-merlin-mode-and-highlighting-of-code-w-errors/12845/2

**Comment by dbuenzli** [comment]
Add `(setq merlin-error-on-single-line t)` to your `.emacs`. Personally I think this should be the default.

**Comment by UnixJunkie** [comment]
+1 for having nice defaults...

**Comment by 3Rafal** [comment]
@UnixJunkie ,
I made a PR that changes the defaults. Can you give me some nice examples of the behavior so that I can test it?

**Comment by UnixJunkie** [comment]
Just take a significant ocaml source file from any project, and change it so that it does not compile anymore.

**Comment by UnixJunkie** [comment]
And yes, this PR https://github.com/ocaml/merlin/pull/1693 changes the default to something I prefer.
Now, the question is, is this what's preferred by most people or not and hence will the PR be merged...

**Comment by nojb** [comment]
> Can you give me some nice examples of the behavior so that I can test it?

I exaplained a typical example that exhibits the issue in https://github.com/ocaml/merlin/pull/1693#issuecomment-1774635100

**Comment by voodoos** [comment]
> Now, the question is, is this what's preferred by most people or not and hence will the PR be merged...

I personally don't have a strong opinion about this. Knowing the scope of the error is useful, but having the whole buffer turn red is not. Do other language plugins have better way to deal with this issue ? Maybe we could underline everything only when more information is asked about the error ? 

Since we had recently a nice collective discussion about keybindings, I will summon the people who took part in it to gather more feedback 🙂 

@Chris00 @mattiase @bbatsov @erikmd @catern

**Comment by bbatsov** [comment]
Depends on what info we can get from the compiler about the error - in CIDER we try to map the errors to a single expression, even if it's multiline. Can someone post a screenshot of the problem, because I don't recall seeing crazy error highlighting in Merlin.

**Comment by nojb** [comment]
> Can someone post a screenshot of the problem, because I don't recall seeing crazy error highlighting in Merlin.

![image](https://github.com/ocaml/merlin/assets/113560/74c65889-5e55-4954-9523-1559a1281e89)

**Comment by bbatsov** [comment]
Yeah, this looks pretty bad indeed. I think most packages would just underline characters 2-19 on line 121 as indicated by the compiler error.

**Comment by mattiase** [comment]
The wholesale highlighting of the entire module struct because of a single mismatch is rubbish of course, but setting `merlin-error-on-single-line` doesn't seem to be the solution. The text becomes more readable in this case but at the price of making the highlighting quite pointless.

Anything preventing us from highlighting the ranges supplied by the error messages? They seem a lot more informative, as in
```
File "broken.ml", line 3, characters 2-16: Expected declaration
File "broken.ml", line 6, characters 6-7: Actual declaration
```
