### ISSUE TITLE
Expand ~ in .merlin files

### ISSUE THREAD

**Issue by infinity0** [ocaml/merlin#469]
The [wiki](https://github.com/the-lambda-church/merlin/wiki/Letting-merlin-locate-go-to-stuff-in-.opam) has the following snippet:

```
CMT /home/me/.opam/4.02.1/build/pcre-ocaml.7.1.2/_build
```

This doesn't generalise well to other developers and adds a maintenance cost to the project. It can be improved a bit like this:

```
CMT /home/*/.opam/4.02.3/build/**/_build
```

but this is not ideal since it wastes time looking in other people's home directories. Being able to specify 

```
CMT ~/.opam/4.02.3/build/**/_build
```

would be much nicer and more usable.

**Comment by gasche** [comment]
I believe this is related to my own request #411 to perform command expansion in `.merlin` files.

In this PR @def-lkb suggested that maybe restricting lookup to opam-specific or ocamlfind-specific variables would be a way to have a saner semantics. What you want can be achieved with either, using

    $(opam config var prefix)/build
    $(ocamlfind printconf path)/../build

(Of course the second is more of a hack, because existence of ocamlfind does not imply existence of opam. It will only work on setups where ocamlfind was installed by opam.)

**Comment by gasche** [comment]
Note: if you create `.merlin.in` file with the content

    CMT %{prefix}%/build/**/_build

then `opam config subst .merlin` will produce a `.merlin` file with the expected content.

**Comment by gasche** [comment]
(I am not trying to say that this should be considered an acceptable workaround. I agree that a stronger support for machine-independent `.merlin` files would be nice.)

**Comment by infinity0** [comment]
Thanks, that's an OK-ish workaround for me for the time being. Yes, I agree that #411 is a superset of this request. It would indeed be better not to have to code any part of the opam path into it.

**Comment by rgrinberg** [comment]
Currently, .merlin files are generated by dune and the longer term goal is to have direct communication between merlin and dune. At which point writing one's own merlin files will become even more obsolete. This all makes me believe that improving the .merlin for those who write them manually is not worth it and therefore I'm closing this issue. Feel free to re-open if there are any objections.
