### ISSUE TITLE
Support/Docs: How To Install Merlin 3 on Windows?

### ISSUE THREAD

**Issue by superherointj** [ocaml/merlin#734]
What are the recommended steps/toolchain/environment for installing Merlin 3 on Windows native?

**Comment by erikmd** [comment]
In order to prepare an Emacs+Tuareg+Merlin installation tutorial for lab sessions on students' Windows laptops in an OCaml teaching unit in Toulouse, I recently tried to recap all ways to run a POSIX environment under Windows and noticed there are at least 5 different ways: relying on Cygwin, MSYS2 (with or without MinGW-w64), VirtualBox, Docker, and the Windows Subsystem for Linux.

All these methods seemed compatible with installing opam (and thereby merlin). But the WSL approach seemed to be the simplest way to do it (while relying on native ELF executables).

In case this helps other people, I have documented the steps to setup this approach (using the [wsl-alias](https://github.com/leongrdic/wsl-alias) wrapper) along with a `.emacs` template for OCaml and Coq bootstrapped with [use-package](https://github.com/jwiegley/use-package), in this repo:
https://github.com/erikmd/tapfa-init-win64.el (*in French*)
[I don't know whether I should mention this info on caml-list as well?]
