### ISSUE TITLE
Different output with single and server commands

### ISSUE THREAD

**Issue by ryskajakub** [ocaml/merlin#741]
When I run ocamlmerlin from command line, server and single commands give me different outputs to the same query. Is it possible that it is not an ocamlmerlin bug? From the help, that I read when running `ocamlmerlin --help`, I assume that the server command is just a speedup and should behave the same. Is my assumption correct? If yes, I'll try to further explain the issue.

-------

command outputs:

using ocamlmerlin 3.0.3:

Request (**server**): ocamlmerlin server locate -look-for ml -position 1:23 -filename /home/coub/test/bucklescript-merlin/src/first.ml < src/first.ml

Response: {"class":"return","value":"Not in environment 'Second.yyxx'","notifications":[],"timing":{"total":4.0,"query":0.0,"reader":0.0,"ppx":0.0,"typer":4.0,"error":0.0}}

Request (**single**):  ocamlmerlin single locate -look-for ml -position 1:23 -filename /home/coub/test/bucklescript-merlin/src/first.ml < src/first.ml

Response: {"class":"return","value":{"file":"/home/coub/test/bucklescript-merlin/src/second.ml","pos":{"line":3,"col":4}},"notifications":[],"timing":{"total":8.0,"query":0.0,"reader":4.0,"ppx":0.0,"typer":4.0,"error":0.0}}

**Comment by trefis** [comment]
Exactly two years later, and a few versions of merlin, I imagine this is going to be hard to reproduce.
To answer the initial question: no it is not normal, the `server` version is, supposedly, only introducing some caching over the `single` version.
So this looks like a bug in the caching.

We've fixed some of theses bugs since the issue was created, and we're still tracking some of them down.

I believe this issue can be closed however. (But feel free to reopen if you can reproduce this on the git version)
