### ISSUE TITLE
Merlin doesn't recognize keyword 'in' in Atom

### ISSUE THREAD

**Issue by Yksu** [ocaml/merlin#764]
So I installed three basic packages for Ocaml on Atom, including merlin which is the source of the error.

<img width="751" alt="screen shot 2017-12-24 at 03 35 00" src="https://user-images.githubusercontent.com/33672752/34323872-9a4ea85a-e85b-11e7-80e2-2d05e88c67dd.png">

I also installed Linter to display the errors. 

On the following basic code, I get the error message that is below, ie the "in" is a syntax error.

<img width="1144" alt="screen shot 2017-12-24 at 03 34 42" src="https://user-images.githubusercontent.com/33672752/34323877-dd12bd84-e85b-11e7-99f8-263d5bd59fdd.png">

If I add ';;' after the Hello world, then there is no more error. Yet I am writing the code in an actual file, not in the console.

**Comment by leviroth** [comment]
That looks like it as it should be. If you try to compile or execute this code, you will see the same syntax error.

(If you want to get into the weeds of double semicolons, the reason is that the second line is an *expression* rather than a *definition*, and expressions need to be separated by a preceding `;;`. See [this line of the OCaml Manual](http://caml.inria.fr/pub/docs/manual-ocaml/modules.html#module-items).)
