### ISSUE TITLE
What options are needed to make merlin accept `sexp_of_*` functions?

### ISSUE THREAD

**Issue by tomsib2001** [ocaml/merlin#783]
I have a project which compiles fine with the command `corebuild -package ppx_sexp_conv normal.native`. When I write things like
```
type foo [@@deriving sexp]

let f = sexp_of_foo
```
Merlin accepts the definition of `foo` but I get `Unbound value sexp_of_foo`. My merlin file looks like
```
PKG sexplib core
EXT sexplib.syntax
```

As an aside, where should I look for documentation on these types of things?

**Comment by trefis** [comment]
`EXT` is not the right thing to use here, try `PKG` instead.

Let me know if that helps!

Note also that I would advise that you switch to [dune](https://github.com/ocaml/dune) instead of using `corebuild` (which isn't really maintained anymore).
This has several advantages, among which:
- automatic `.merlin` generation when you compile
- [extensive documentation](https://dune.readthedocs.io/en/latest/) (don't be afraid by the "jbuilder" name you'll see everywhere, it's the previous name for dune, they are currently in a transition period)

**Comment by tomsib2001** [comment]
Thanks! Changing `EXT` to `PKG` did not help, but switching to `jbuilder`/`dune` did. If anyone stumbles upon this thread, here is what I did:
- Create a `jbuild` file containing:
```(jbuild_version 1)


(executable
 ((name normal)
  (libraries (core))
  (preprocess (pps (ppx_jane)))
))
```

- run the command
```
jbuilder build normal.exe
```

**Comment by trefis** [comment]
No problem!

Out of curiosity, what does the .merlin generated by `dune` contain?

**Comment by tomsib2001** [comment]
It's a mouthful:
```
B _build/default
FLG -ppx '/home/thomas/projets/pbft-ocaml/_build/default/.ppx/ppx_jane/ppx.exe --as-ppx'
FLG -w -40
PKG base
PKG base.caml
PKG base.md5
PKG base.shadow_stdlib
PKG bigarray
PKG bin_prot
PKG bin_prot.shape
PKG core
PKG core_kernel
PKG core_kernel.base_for_tests
PKG fieldslib
PKG jane-street-headers
PKG ppx_assert.runtime-lib
PKG ppx_bench.runtime-lib
PKG ppx_compare.runtime-lib
PKG ppx_expect.collector
PKG ppx_expect.common
PKG ppx_expect.config
PKG ppx_hash.runtime-lib
PKG ppx_inline_test.config
PKG ppx_inline_test.runtime-lib
PKG sexplib
PKG sexplib.0
PKG sexplib.unix
PKG spawn
PKG stdio
PKG threads
PKG threads.posix
PKG typerep
PKG unix
PKG variantslib
S .
```
