### ISSUE TITLE
merlin-locate doesn't handle local binding properly

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/merlin#806]
```ocaml
let foo () = ()

let () =
  let foo () = () in
  foo ()
```

In the example above, going to definition on the last occurrence of foo will jump to the 1st definition, rather than the 2nd one.

**Comment by trefis** [comment]
The problem is not exactly related to shadowing, but rather that the current implementation of locate doesn't handle local bindings properly (if your local binding doesn't shadow a global one then things will work properly because of reasons, but if it does then well… it's sad).

I hope to fix this in a couple of weeks.
