### ISSUE TITLE
Merlin misses Error: The type of this expression …, contains type variables that cannot be generalized

### ISSUE THREAD

**Issue by copy** [ocaml/merlin#819]
For example in this code in a standalone .ml file:

```ocaml
let f () x = Some x
let g = f ()
```

Merlin doesn't show any error, while compilation of the file fails:

```
% ocamlbuild test.byte --
File "test.ml", line 2, characters 4-5:
Error: The type of this expression, '_weak1 -> '_weak1 option,
       contains type variables that cannot be generalized
```

**Comment by trefis** [comment]
That is expected I think.
It makes sense for the compiler to report such errors, because when you call the compiler you're (usually) done writing the program. But when merlin runs you're still writing code and nothing prevents you from adding a line like `let _ = g 3` which would make that error disappear.
We try to avoid reporting errors that get too noisy when one is still actively editing the code.

**Comment by copy** [comment]
That makes sense, thanks for the explanation. I'll close this then.
