### ISSUE TITLE
not exhausted binary path in merlin.vim

### ISSUE THREAD

**Issue by Dead-User** [ocaml/merlin#872]
the binary of ocamlmerlin may be installed to .opam/default/bin, but this directory is not searched by
merlin#FindBinary in merlin.vim such that  ocamlmerlin is not found and the plugin fails. manually adding
the actual path solves this problem.

**Comment by trefis** [comment]
I guess you're right. We must have never noticed because merlin's binary is usually in people's PATH, but indeed looking at `autoload/merlin.vim` and `plugin/merlin.vim` we're checking if either `s:c.merlin_home/ocamlmerlin` or `s:c.merlin_home/ocamlmerlin.native` exist, which I believe translate to `$OPAMROOT/switch/share/ocamlmerlin` and `$OPAMROOT/switch/share/ocamlmerlin.native`.

@let-def: do you agree with that interpretation? Should we add one `:h` to the definition of `s:c.merlin_home` and start looking for `s:c.merlin_home."/bin/".v:val`?
