### ISSUE TITLE
Disable "this pattern-matching is not exhaustive"

### ISSUE THREAD

**Issue by chengtie** [ocaml/merlin#920]
I'm new to Merlin.

I would like to know how to disable the warnings 8 "this pattern-matching is not exhaustive". Most of time, I know it is not exhaustive.

Cheers

**Comment by raphael-proust** [comment]
You can add a case `_ -> assert false`. This will help with debugging in the future because `assert false` is printed with location information. (IIRC, I'm not 100% sure.)

You can use GADTs to make the non-exhaustiveness ok.

You can use `[@@@ocaml.warning "-8"]`. These suppress the warning without changing the code. They are called attributes (in case you need to search more info about them).

Here's a SO questions similar to yours https://stackoverflow.com/questions/46489249/use-ocaml-warning-atttribute-to-disable-warning-8-unexhaustive-match I recommend you also read the comments on the answer for more modern use of attributes.

**Comment by chengtie** [comment]
I don't want to change my code.

However, we still need to add `[@@@ocaml.warning "-8"]` to the file where we want to disable the warning, right?

I thought this warning should be just a parameter of merlin to enable or disable.

**Comment by raphael-proust** [comment]
You can add `FLG -w -8` to your `.merlin` file.

More details on the `.merlin` file: https://github.com/ocaml/merlin/wiki/project-configuration  
More details on warning flags: https://caml.inria.fr/pub/docs/manual-ocaml/comp.html

**Comment by chengtie** [comment]
> You can add `FLG -w -8` to your `.merlin` file.
> 
> More details on the `.merlin` file: https://github.com/ocaml/merlin/wiki/project-configuration
> More details on warning flags: https://caml.inria.fr/pub/docs/manual-ocaml/comp.html

It works... thank you...
