### ISSUE TITLE
merlin-locate is confused by tabs (not a valid identifier)

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/merlin#975]
~~~ocaml
let foo = 1
	let baz = foo
~~~
(the leading space before `let baz` is a tab character)
In emacs, place point anywhere in the second `foo` and call `merlin-locate`, it will say `not a valid identifier`.

**Comment by trefis** [comment]
I just tried this and could not reproduce, regardless of the editor I used (emacs or vim).

**Comment by SkySkimmer** [comment]
From `emacs -q`, `eval-buffer` in `merlin.el` (it complains about not found merlin-ac). merlin-locate works fine on regular files and reproduces the bug on the example with tabs.
emacs 26.1
merlin 3.3.1

**Comment by trefis** [comment]
Right right, I didn't mean to imply that there wasn't any issue. I'm just guessing that if there is one, it's probably due to some interaction with another part of your config. And I don't know enough about emacs to help any further.
I would guess any option related to the representation of tabs should be looked at; but I don't know what they are.

**Comment by let-def** [comment]
I managed to reproduce and make a quick fix.

**Comment by SkySkimmer** [comment]
Thanks!
