### ISSUE TITLE
add support for formatting in the lsp

### ISSUE THREAD

**Issue by tcoopman** [ocaml/merlin#980]
The language server protocol has capabilities for formatting (https://microsoft.github.io/language-server-protocol/specification). It would be nice if the `merlin-lsp` has support for that as well

**Comment by trefis** [comment]
This is outside of merlin's scope, you should look into [ocaml-ppx/ocamlformat](https://github.com/ocaml-ppx/ocamlformat).

**Comment by tcoopman** [comment]
I know about ocamlformat. But I was thinking that because the language server protocol has support for formatting the merlin language server could support it as well, maybe via ocamlformat.

But if this is closed I guess the goal of the lsp is not to support the whole protocol?

**Comment by let-def** [comment]
The goal of merlin itself is not to support the whole protocol, however merlin-lsp may be the right place to do the plumbing.
@andreypopp, @Khady & @gpetiot might have a more informed opinion on the problem?

**Comment by Khady** [comment]
I am an outsider, but I had the impression that some people wanted to have a full LSP server in dune. That could call other tools such as merlin and ocamlformat.

Some editors such as emacs are also able to have multiple LSP servers running for a single file. Which means that ocamlformat could have its own LSP server handling only the formatting. While merlin-lsp keeps its current scope. And both would be called by the editor when necessary. I don't know what is the support in more popular editors (vim, vscode, atom).

Otherwise it depends what scope you want to give to merlin-lsp. If you want to make it the single LSP server for OCaml/Reason, it should indeed be possible to implement the plumbing to call ocamlformat, rotor or any other tool.

**Comment by let-def** [comment]
I prefer to keep the scope of merlin as restricted as possible. We simply don't have the resources to be too ambitious.

Cooperating with dune sounds good.
However I would like to avoid having many LSP servers, I have enough crap running on my machine and configuring one service for each feature won't be a nice experience.

**Comment by rgrinberg** [comment]
The main goal of having an LSP server in dune was to editor functionality related to dune itself. Things like editing dune files, triggering builds more easily. However, I'm for deep integration with other OCaml LSP servers if you think that is the right way to go forward.

**Comment by tcoopman** [comment]
I don't think that a lot of editors have support for running multiple LSP servers for one file (also wondering how that works in case of overlapping capabilities).

It would be nice if there is one `ocaml/reason` LSP that delegates capabilities to the correct tools. Not sure how feasible this is though.

**Comment by rgrinberg** [comment]
This issue is tracked here: https://github.com/ocaml/ocaml-lsp/issues/8
